"""GitHub PR creation for AI-generated drafts."""

from __future__ import annotations

import logging
import re
import subprocess
from pathlib import Path
from typing import Any

from github import Github

logger = logging.getLogger(__name__)


def sanitize_branch_name(title: str, date: str) -> str:
    """
    Sanitize title into valid branch name.

    Rules:
    - Lowercase
    - Replace spaces with hyphens
    - Remove special characters
    - Truncate to 50 chars
    - Prepend 'draft/'
    """
    # Lowercase and replace spaces
    name = title.lower().replace(" ", "-")

    # Remove special characters
    name = re.sub(r"[^a-z0-9-]", "", name)

    # Remove consecutive hyphens
    name = re.sub(r"-+", "-", name)

    # Truncate
    name = name[:50].strip("-")

    return f"draft/{name}-{date}"


def format_pr_description(pipeline_results: dict[str, Any], branch_name: str) -> str:
    """Format PR description from pipeline results."""
    item = pipeline_results["queue_item"]
    category = pipeline_results["category"]
    queries = pipeline_results.get("queries", [])
    sources_count = pipeline_results.get("sources_count", 0)
    passes = pipeline_results.get("passes", {})

    # Status emojis
    status_emoji = {"success": "✅", "partial": "⚠️", "failed": "❌"}

    def status(key: str) -> str:
        state = passes.get(key, "failed")
        return f"{status_emoji.get(state, '❓')} {state.capitalize()}"

    # Extract artifact path from branch name
    topic_date = branch_name.replace("draft/", "")
    artifacts_path = f"drafts/artifacts/{topic_date}"

    description = f"""## Generated Draft

**Queue Item**: {item.get("title", "Unknown")}
**Category**: {category}
**Source URL**: {item.get("url", "N/A")}
**Generated**: {item.get("timestamp", "N/A")}

### Pipeline Summary

**Pass 1 - Query Generation**: {status("query_gen")}
Generated {len(queries)} search queries

**Pass 2 - Source Gathering**: {status("search")}
Found {sources_count} relevant sources via Exa AI

**Pass 3 - Outline Synthesis**: {status("outline")}
Created structured outline

**Pass 4 - Draft Expansion**: {status("draft")}
Generated full draft

### Search Queries Used

"""

    for i, query in enumerate(queries, 1):
        description += f"{i}. {query}\n"

    description += f"""
### Review Checklist

- [ ] Verify technical accuracy
- [ ] Check template structure adaptation
- [ ] Add personal insights and understanding
- [ ] Refine explanations and examples
- [ ] Verify all references and citations
- [ ] Fill any TODO sections

### Artifacts

📁 [View all artifacts](../../tree/{branch_name}/{artifacts_path})

- `queries.json` - Generated search queries with reasoning
- `sources.json` - All Exa search results with URLs and scores
- `outline.md` - Synthesized outline before expansion
- `errors.log` - Any errors encountered (if applicable)

---

*This draft was automatically generated by the AI Draft Generation workflow. Please review and refine before merging.*
"""

    return description


class DraftPRCreator:
    """Handles Git operations and PR creation."""

    def __init__(self, repo_path: Path, github_token: str):
        """Initialize PR creator."""
        self.repo_path = repo_path
        self.github_token = github_token
        self.github_client = None
        self.repo = None

    def _run_git(self, *args: str) -> str:
        """Run git command in repo directory."""
        result = subprocess.run(
            ["git", "-C", str(self.repo_path)] + list(args),
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()

    def create_branch(self, branch_name: str) -> None:
        """Create and checkout new branch from main."""
        logger.info(f"Creating branch: {branch_name}")

        # Ensure we're on main and up to date
        self._run_git("checkout", "main")
        self._run_git("pull", "origin", "main")

        # Delete local branch if it exists
        try:
            self._run_git("branch", "-D", branch_name)
            logger.info(f"Deleted existing local branch: {branch_name}")
        except subprocess.CalledProcessError:
            pass  # Branch doesn't exist locally, that's fine

        # Create new branch
        self._run_git("checkout", "-b", branch_name)

    def commit_files(self, files: list[Path], message: str) -> str:
        """Commit files and return commit SHA."""
        logger.info(f"Committing {len(files)} files")

        # Stage files
        for file in files:
            self._run_git("add", str(file))

        # Commit
        self._run_git("commit", "-m", message)

        # Get commit SHA
        sha = self._run_git("rev-parse", "HEAD")
        return sha

    def push_branch(self, branch_name: str) -> None:
        """Push branch to origin, overwriting if it exists."""
        logger.info(f"Pushing branch: {branch_name}")

        # Force push to overwrite any existing remote branch from previous runs
        # This is safe for draft branches since they're regenerated each time
        self._run_git("push", "-u", "origin", branch_name, "--force")

    def create_pull_request(
        self,
        branch_name: str,
        title: str,
        description: str,
        labels: list[str] | None = None,
    ) -> dict[str, Any]:
        """
        Create pull request via GitHub API.

        Returns dict with 'number' and 'url'
        """
        logger.info(f"Creating PR for branch: {branch_name}")

        # Initialize GitHub client
        self.github_client = Github(self.github_token)

        # Get repository (assumes format: owner/repo from git remote)
        remote_url = self._run_git("remote", "get-url", "origin")

        # Parse owner/repo from URL
        # Handles: git@github.com:owner/repo.git or https://github.com/owner/repo.git
        match = re.search(r"github\.com[:/]([^/]+)/([^/\.]+)", remote_url)
        if not match:
            raise ValueError(f"Could not parse GitHub repo from remote: {remote_url}")

        owner, repo_name = match.groups()
        self.repo = self.github_client.get_repo(f"{owner}/{repo_name}")

        # Check if PR already exists for this branch
        existing_prs = self.repo.get_pulls(state="open", head=f"{owner}:{branch_name}")
        for existing_pr in existing_prs:
            logger.info(
                f"PR already exists: #{existing_pr.number} - {existing_pr.html_url}"
            )
            logger.info("Updating existing PR description")
            existing_pr.edit(body=description)

            # Add labels if specified
            if labels:
                existing_pr.add_to_labels(*labels)

            return {"number": existing_pr.number, "url": existing_pr.html_url}

        # Create new PR
        pr = self.repo.create_pull(
            title=title, body=description, head=branch_name, base="main"
        )

        # Add labels if specified
        if labels:
            pr.add_to_labels(*labels)

        logger.info(f"Created PR #{pr.number}: {pr.html_url}")

        return {"number": pr.number, "url": pr.html_url}
