name: Update README with directory tables

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          echo "Updating README..."
          # Add your commands to update the README here
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          python run update_readme.py
          git add README.md
          git commit -m "Update README with directory tables"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update README with directory tables"
          else
            echo "No changes to commit"
          fi
